import { glob, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

import { COMMON_ERROR_STATUS_MAP } from '@orpc/server'

const getStatusCode = (errorCode: string): number => {
  const prefix = errorCode.split('::')[0]
  return prefix in COMMON_ERROR_STATUS_MAP
    ? COMMON_ERROR_STATUS_MAP[prefix as keyof typeof COMMON_ERROR_STATUS_MAP]
    : 500
}

interface GenerateErrorStatusMapOptions {
  sourceDirs?: string[]
  outputFile: string
}

export const generateErrorStatusMap = async ({
  sourceDirs,
  outputFile
}: GenerateErrorStatusMapOptions): Promise<void> => {
  const output = outputFile
  const errorCodes = new Set<string>()

  for (const cwd of sourceDirs ?? ['./src']) {
    for await (const file of glob('**/*.ts', { cwd, exclude: ['**/*.gen.ts'] })) {
      const source = await readFile(join(cwd, file), 'utf8')
      for (const match of source.matchAll(/(['"`])([A-Z][A-Z0-9_]*::[A-Z][A-Z0-9_]*)\1/g)) {
        errorCodes.add(match[2])
      }
    }
  }

  const codes = [...errorCodes].sort()
  const entries = codes.map((code) => `  '${code}': ${getStatusCode(code)}`)
  const content = [
    '// Generated by scripts/generate-error-status-map.ts. Do not edit manually.',
    "import { COMMON_ERROR_STATUS_MAP } from '@orpc/openapi'",
    '',
    `export type ErrorCode = ${codes.length > 0 ? codes.map((code) => `'${code}'`).join(' | ') : 'never'}`,
    '',
    'export const ErrorStatusMap = {',
    ['  ...COMMON_ERROR_STATUS_MAP', ...entries].join(',\n'),
    '}',
    ''
  ].join('\n')

  try {
    if ((await readFile(output, 'utf8')) === content) {
      return
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      throw error
    }
  }
  return writeFile(output, content)
}
