name: release

on:
  push:
    branches: ['main']

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  packages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['lts/*']

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i
      - name: Unit Test
        run: pnpm test

      - name: Build packages
        run: pnpm -r build

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'release: release packages & update CHANGELOG.md'
          title: '📦 Update Packages Version'
          publish: pnpm changeset-publish
          version: pnpm changeset-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to jsr.io
        if: steps.changesets.outputs.published == 'true'
        run: pnpm dlx @qingshaner/jsr-release publish --changesetReleases='${{ steps.changesets.outputs.publishedPackages }}'

      - name: CNPM sync the latest published package
        if: steps.changesets.outputs.published == 'true'
        run: |
          echo '${{ steps.changesets.outputs.publishedPackages }}' | jq -c '.[]' | while read package; do
            NPM_PACKAGE_NAME=$(echo $package | jq -r '.name')
            echo "Syncing CNPM $NPM_PACKAGE_NAME"
            LOG_ID=$(curl -X PUT "https://registry.npmmirror.com/${NPM_PACKAGE_NAME}/sync?publish=true&nodeps=false" | jq -r '.logId')
            echo "Log URL: https://registry.npmmirror.com/-/package/${NPM_PACKAGE_NAME}/syncs/${LOG_ID}/log"
          done
